final Map<String, Map<String, String>> localizedText = {
  "TR": {
    "start": "BAŞLA",
    "settings": "AYARLAR",
    "shop_title": "ŞEKER MARKET",
    "sound": "Ses Efektleri",
    "music": "Müzik",
    "lang": "Dil (Language)",
    "close": "KAPAT",
    "buy": "AL",
    "score": "SKOR",
    "daily_test": "GÜNLÜK TEST",
    "daily_done": "BUGÜNLÜK TAMAM",
    "slogan": "Refleksini değil, beynini tamir et.",
    "reverse": "TERSİNE!",
    "same": "AYNI YÖNE!",
    "swipe": "KAYDIR",
    "dont_touch": "DOKUNMA!",
    "wait": "BEKLE...",
    "math_q": "DOĞRU MU?",
    "emoji_q": "HANGİSİ?",
    "not_color_q": "OLMAYANA BAS!",
    "wrong": "YANLIŞ",
    "correct": "DOĞRU",
    "color_ink": "YAZININ RENGİ?",
    "color_text": "YAZAN RENK?",
    "game_over_time": "SÜRE BİTTİ!",
    "game_over_touch": "YANLIŞ DOKUNUŞ!",
    "game_over_hand": "ELİNİ ÇEK!",
    "game_over_wrong": "HATALI HAMLE!",
    "game_report":"Oyun Sonu Raporu!",
    "brain_age": "Beyin Yaşın",
    "fever": "AŞIRI YÜKLENME!",
    "shield_broken": "KALKAN KIRILDI!",
    "revive": "CANLAN",
    "watch_ad": "Reklam İzle",
    "ad_loading": "Reklam Yükleniyor...",
    "bag": "Çanta",
    "retry": "TEKRAR",
    "collected": "Kazanılan",
    "penalty": "Ceza",
    "item_warning": "Aktif Eşyalar Var!",
    "revive_active_msg": "İKİNCİ ŞANS AKTİF!",
    "balance": "Bakiye",
    "reflex": "Refleks",
    "perception": "Mantık",
    "logic": "Algı",
    "emotion":"Duygu",
    
    // --- MARKET BAŞLIKLARI ---
    "sec_powerups": "GÜÇLENDİRMELER",
    "sec_modes": "MOD İKSİRLERİ",
    "sec_repair": "BEYİN ONARIMI",

    // --- EŞYALAR ---
    "item_heart": "İkinci Şans",
    "desc_heart": "1 Hatayı Affeder",
    "item_time": "Zaman İksiri",
    "desc_time": "Zamanı Yavaşlatır",
    "item_sugar": "Şeker Yağmuru",
    "desc_sugar": "2x Şeker Kazancı",
    "item_sugar_x3": "Şeker Patlaması",
    "desc_sugar_x3": "3x Şeker Kazancı!",
    
    "item_reflex": "Saf Refleks",
    "desc_reflex": "Sadece Yön Soruları",
    "item_math": "Saf Mantık",
    "desc_math": "Sadece Matematik",
    "item_color": "Saf Algı",
    "desc_color": "Sadece Renkler",
    "item_emoji": "Saf Duygu",
    "desc_emoji": "Sadece Emojiler",
    
    // --- ONARIM ---
    "repair_reflex": "Refleks Lobu",
    "repair_logic": "Mantık Lobu",
    "repair_perception": "Algı Lobu",
    "repair_emotion": "Duygu Lobu",
    "repair_control": "Kontrol Lobu",
    "repair_general": "Genel Stabilite",
  },
  "EN": {
    "start": "START",
    "settings": "SETTINGS",
    "shop_title": "SUGAR MARKET",
    "sound": "SFX Volume",
    "music": "Music Volume",
    "daily_test": "DAILY TEST",
    "daily_done": "DONE FOR TODAY",
    "slogan": "Fix your brain, not just reflexes.",
    "lang": "Language (Dil)",
    "close": "CLOSE",
    "buy": "BUY",
    "score": "SCORE",
    "reverse": "REVERSE!",
    "same": "SAME DIR!",
    "swipe": "SWIPE",
    "dont_touch": "DON'T TOUCH!",
    "wait": "WAIT...",
    "math_q": "CORRECT?",
    "emoji_q": "WHICH ONE?",
    "not_color_q": "TAP NOT COLOR!",
    "wrong": "WRONG",
    "correct": "CORRECT",
    "color_ink": "INK COLOR?",
    "color_text": "TEXT MEANING?",
    "game_over_time": "TIME UP!",
    "game_over_touch": "BAD TOUCH!",
    "game_over_hand": "HANDS OFF!",
    "game_report": "Game Report!",
    "game_over_wrong": "WRONG MOVE!",
    "brain_age": "Brain Age",
    "fever": "FEVER MODE!",
    "shield_broken": "SHIELD BROKEN!",
    "revive": "REVIVE",
    "watch_ad": "Watch Ad",
    "ad_loading": "Loading Ad...",
    "bag": "Bag",
    "retry": "RETRY",
    "collected": "Collected",
    "penalty": "Penalty",
    "item_warning": "Active Items!",
    "revive_active_msg": "SECOND CHANCE ACTIVE!",
    "balance": "Balance",
    "reflex": "Reflex",
    "perception": "Perception",
    "logic": "Logic",
    "emotion":"Emotion",

    // --- MARKET HEADERS ---
    "sec_powerups": "POWER-UPS",
    "sec_modes": "MODE POTIONS",
    "sec_repair": "BRAIN REPAIR",

    // --- ITEMS ---
    "item_heart": "Second Chance",
    "desc_heart": "Ignores 1 Mistake",
    "item_time": "Time Potion",
    "desc_time": "Slows Down Time",
    "item_sugar": "Sugar Rain",
    "desc_sugar": "2x Candy Gain",
    "item_sugar_x3": "Sugar Rush",
    "desc_sugar_x3": "3x Candy Gain!",

    "item_reflex": "Pure Reflex",
    "desc_reflex": "Only Direction Tasks",
    "item_math": "Pure Logic",
    "desc_math": "Only Math Tasks",
    "item_color": "Pure Perception",
    "desc_color": "Only Color Tasks",
    "item_emoji": "Pure Emotion",
    "desc_emoji": "Only Emoji Tasks",

    // --- REPAIR ---
    "repair_reflex": "Reflex Lobe",
    "repair_logic": "Logic Lobe",
    "repair_perception": "Perception Lobe",
    "repair_emotion": "Emotion Lobe",
    "repair_control": "Control Lobe",
    "repair_general": "General Stability",
  },
};